steps:
# Use maven to package the app
- name: maven:3-jdk-11
  entrypoint: mvn
  args: ['package']
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/galvanic-idiom-362501/restful-app-hw5', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/galvanic-idiom-362501/restful-app-hw5']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'restful-app-hw5', '--image', 'gcr.io/galvanic-idiom-362501/restful-app-hw5', '--region', 'us-east4', '--platform', 'managed']
images:
- gcr.io/galvanic-idiom-362501/restful-app-hw5
